// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.1
// source: realworld/v1/realworld.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *AuthRequest_User      `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetUser() *AuthRequest_User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *RegisterRequest_User  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetUser() *RegisterRequest_User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	User          *UpdateUserRequest_User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserRequest) GetUser() *UpdateUserRequest_User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type FollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserRequest) Reset() {
	*x = FollowUserRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserRequest) ProtoMessage() {}

func (x *FollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserRequest.ProtoReflect.Descriptor instead.
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{4}
}

func (x *FollowUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ListArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Favorited     string                 `protobuf:"bytes,3,opt,name=favorited,proto3" json:"favorited,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesRequest) Reset() {
	*x = ListArticlesRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesRequest) ProtoMessage() {}

func (x *ListArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{5}
}

func (x *ListArticlesRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ListArticlesRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ListArticlesRequest) GetFavorited() string {
	if x != nil {
		return x.Favorited
	}
	return ""
}

func (x *ListArticlesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListArticlesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FeedArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedArticlesRequest) Reset() {
	*x = FeedArticlesRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedArticlesRequest) ProtoMessage() {}

func (x *FeedArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedArticlesRequest.ProtoReflect.Descriptor instead.
func (*FeedArticlesRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{6}
}

func (x *FeedArticlesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FeedArticlesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{7}
}

func (x *GetArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type CreateArticleRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Article       *CreateArticleRequest_Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{9}
}

func (x *CreateArticleRequest) GetArticle() *CreateArticleRequest_Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type UpdateArticleRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Slug          string                        `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Article       *UpdateArticleRequest_Article `protobuf:"bytes,2,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdateArticleRequest) GetArticle() *UpdateArticleRequest_Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type AddCommentsRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Slug          string                      `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Comment       *AddCommentsRequest_Comment `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentsRequest) Reset() {
	*x = AddCommentsRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentsRequest) ProtoMessage() {}

func (x *AddCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentsRequest.ProtoReflect.Descriptor instead.
func (*AddCommentsRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{11}
}

func (x *AddCommentsRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *AddCommentsRequest) GetComment() *AddCommentsRequest_Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{12}
}

func (x *GetCommentsRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCommentRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *DeleteCommentRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FavoriteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteArticleRequest) Reset() {
	*x = FavoriteArticleRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteArticleRequest) ProtoMessage() {}

func (x *FavoriteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteArticleRequest.ProtoReflect.Descriptor instead.
func (*FavoriteArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{14}
}

func (x *FavoriteArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type UserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserReply_User        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReply) Reset() {
	*x = UserReply{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReply) ProtoMessage() {}

func (x *UserReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReply.ProtoReflect.Descriptor instead.
func (*UserReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{15}
}

func (x *UserReply) GetUser() *UserReply_User {
	if x != nil {
		return x.User
	}
	return nil
}

type ProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ProfileReply_Profile  `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileReply) Reset() {
	*x = ProfileReply{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileReply) ProtoMessage() {}

func (x *ProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileReply.ProtoReflect.Descriptor instead.
func (*ProfileReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{16}
}

func (x *ProfileReply) GetProfile() *ProfileReply_Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type SingleArticleReply struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Article       *SingleArticleReply_Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleArticleReply) Reset() {
	*x = SingleArticleReply{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleArticleReply) ProtoMessage() {}

func (x *SingleArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleArticleReply.ProtoReflect.Descriptor instead.
func (*SingleArticleReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{17}
}

func (x *SingleArticleReply) GetArticle() *SingleArticleReply_Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type MultipleArticleReply struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Articles      []*MultipleArticleReply_Article `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	ArticlesCount int32                           `protobuf:"varint,2,opt,name=articlesCount,proto3" json:"articlesCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleArticleReply) Reset() {
	*x = MultipleArticleReply{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleArticleReply) ProtoMessage() {}

func (x *MultipleArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleArticleReply.ProtoReflect.Descriptor instead.
func (*MultipleArticleReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{18}
}

func (x *MultipleArticleReply) GetArticles() []*MultipleArticleReply_Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *MultipleArticleReply) GetArticlesCount() int32 {
	if x != nil {
		return x.ArticlesCount
	}
	return 0
}

type SingleCommentReply struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Comment       *SingleCommentReply_Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleCommentReply) Reset() {
	*x = SingleCommentReply{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleCommentReply) ProtoMessage() {}

func (x *SingleCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleCommentReply.ProtoReflect.Descriptor instead.
func (*SingleCommentReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{19}
}

func (x *SingleCommentReply) GetComment() *SingleCommentReply_Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type MultipleCommentReply struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Comments      []*MultipleCommentReply_Comment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleCommentReply) Reset() {
	*x = MultipleCommentReply{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleCommentReply) ProtoMessage() {}

func (x *MultipleCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleCommentReply.ProtoReflect.Descriptor instead.
func (*MultipleCommentReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{20}
}

func (x *MultipleCommentReply) GetComments() []*MultipleCommentReply_Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type ListTagsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsReply) Reset() {
	*x = ListTagsReply{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsReply) ProtoMessage() {}

func (x *ListTagsReply) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsReply.ProtoReflect.Descriptor instead.
func (*ListTagsReply) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{21}
}

func (x *ListTagsReply) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AuthRequest_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest_User) Reset() {
	*x = AuthRequest_User{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest_User) ProtoMessage() {}

func (x *AuthRequest_User) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest_User.ProtoReflect.Descriptor instead.
func (*AuthRequest_User) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AuthRequest_User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthRequest_User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterRequest_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest_User) Reset() {
	*x = RegisterRequest_User{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest_User) ProtoMessage() {}

func (x *RegisterRequest_User) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest_User.ProtoReflect.Descriptor instead.
func (*RegisterRequest_User) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RegisterRequest_User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest_User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest_User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UpdateUserRequest_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest_User) Reset() {
	*x = UpdateUserRequest_User{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest_User) ProtoMessage() {}

func (x *UpdateUserRequest_User) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest_User.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest_User) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{2, 0}
}

func (x *UpdateUserRequest_User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest_User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequest_User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserRequest_User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateUserRequest_User) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type CreateArticleRequest_Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	TagList       []string               `protobuf:"bytes,4,rep,name=tagList,proto3" json:"tagList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest_Article) Reset() {
	*x = CreateArticleRequest_Article{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest_Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest_Article) ProtoMessage() {}

func (x *CreateArticleRequest_Article) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest_Article.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest_Article) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{9, 0}
}

func (x *CreateArticleRequest_Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRequest_Article) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateArticleRequest_Article) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateArticleRequest_Article) GetTagList() []string {
	if x != nil {
		return x.TagList
	}
	return nil
}

type UpdateArticleRequest_Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest_Article) Reset() {
	*x = UpdateArticleRequest_Article{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest_Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest_Article) ProtoMessage() {}

func (x *UpdateArticleRequest_Article) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest_Article.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest_Article) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{10, 0}
}

func (x *UpdateArticleRequest_Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateArticleRequest_Article) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateArticleRequest_Article) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type AddCommentsRequest_Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentsRequest_Comment) Reset() {
	*x = AddCommentsRequest_Comment{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentsRequest_Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentsRequest_Comment) ProtoMessage() {}

func (x *AddCommentsRequest_Comment) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentsRequest_Comment.ProtoReflect.Descriptor instead.
func (*AddCommentsRequest_Comment) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{11, 0}
}

func (x *AddCommentsRequest_Comment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type UserReply_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReply_User) Reset() {
	*x = UserReply_User{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReply_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReply_User) ProtoMessage() {}

func (x *UserReply_User) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReply_User.ProtoReflect.Descriptor instead.
func (*UserReply_User) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{15, 0}
}

func (x *UserReply_User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserReply_User) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserReply_User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserReply_User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserReply_User) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type ProfileReply_Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following     bool                   `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileReply_Profile) Reset() {
	*x = ProfileReply_Profile{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileReply_Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileReply_Profile) ProtoMessage() {}

func (x *ProfileReply_Profile) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileReply_Profile.ProtoReflect.Descriptor instead.
func (*ProfileReply_Profile) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{16, 0}
}

func (x *ProfileReply_Profile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProfileReply_Profile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *ProfileReply_Profile) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProfileReply_Profile) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type SingleArticleReply_Article struct {
	state          protoimpl.MessageState             `protogen:"open.v1"`
	Slug           string                             `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title          string                             `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                             `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Body           string                             `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	TagList        []string                           `protobuf:"bytes,5,rep,name=tagList,proto3" json:"tagList,omitempty"`
	CreatedAt      string                             `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt      string                             `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Favorited      bool                               `protobuf:"varint,8,opt,name=favorited,proto3" json:"favorited,omitempty"`
	FavoritesCount int32                              `protobuf:"varint,9,opt,name=favoritesCount,proto3" json:"favoritesCount,omitempty"`
	Author         *SingleArticleReply_Article_Author `protobuf:"bytes,10,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SingleArticleReply_Article) Reset() {
	*x = SingleArticleReply_Article{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleArticleReply_Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleArticleReply_Article) ProtoMessage() {}

func (x *SingleArticleReply_Article) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleArticleReply_Article.ProtoReflect.Descriptor instead.
func (*SingleArticleReply_Article) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{17, 0}
}

func (x *SingleArticleReply_Article) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SingleArticleReply_Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SingleArticleReply_Article) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SingleArticleReply_Article) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SingleArticleReply_Article) GetTagList() []string {
	if x != nil {
		return x.TagList
	}
	return nil
}

func (x *SingleArticleReply_Article) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SingleArticleReply_Article) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SingleArticleReply_Article) GetFavorited() bool {
	if x != nil {
		return x.Favorited
	}
	return false
}

func (x *SingleArticleReply_Article) GetFavoritesCount() int32 {
	if x != nil {
		return x.FavoritesCount
	}
	return 0
}

func (x *SingleArticleReply_Article) GetAuthor() *SingleArticleReply_Article_Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type SingleArticleReply_Article_Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following     bool                   `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleArticleReply_Article_Author) Reset() {
	*x = SingleArticleReply_Article_Author{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleArticleReply_Article_Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleArticleReply_Article_Author) ProtoMessage() {}

func (x *SingleArticleReply_Article_Author) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleArticleReply_Article_Author.ProtoReflect.Descriptor instead.
func (*SingleArticleReply_Article_Author) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{17, 0, 0}
}

func (x *SingleArticleReply_Article_Author) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SingleArticleReply_Article_Author) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *SingleArticleReply_Article_Author) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SingleArticleReply_Article_Author) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type MultipleArticleReply_Article struct {
	state          protoimpl.MessageState               `protogen:"open.v1"`
	Slug           string                               `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title          string                               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TagList        []string                             `protobuf:"bytes,4,rep,name=tagList,proto3" json:"tagList,omitempty"`
	CreatedAt      string                               `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt      string                               `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Favorited      bool                                 `protobuf:"varint,7,opt,name=favorited,proto3" json:"favorited,omitempty"`
	FavoritesCount int32                                `protobuf:"varint,8,opt,name=favoritesCount,proto3" json:"favoritesCount,omitempty"`
	Author         *MultipleArticleReply_Article_Author `protobuf:"bytes,9,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MultipleArticleReply_Article) Reset() {
	*x = MultipleArticleReply_Article{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleArticleReply_Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleArticleReply_Article) ProtoMessage() {}

func (x *MultipleArticleReply_Article) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleArticleReply_Article.ProtoReflect.Descriptor instead.
func (*MultipleArticleReply_Article) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{18, 0}
}

func (x *MultipleArticleReply_Article) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *MultipleArticleReply_Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MultipleArticleReply_Article) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MultipleArticleReply_Article) GetTagList() []string {
	if x != nil {
		return x.TagList
	}
	return nil
}

func (x *MultipleArticleReply_Article) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MultipleArticleReply_Article) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *MultipleArticleReply_Article) GetFavorited() bool {
	if x != nil {
		return x.Favorited
	}
	return false
}

func (x *MultipleArticleReply_Article) GetFavoritesCount() int32 {
	if x != nil {
		return x.FavoritesCount
	}
	return 0
}

func (x *MultipleArticleReply_Article) GetAuthor() *MultipleArticleReply_Article_Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type MultipleArticleReply_Article_Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following     bool                   `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleArticleReply_Article_Author) Reset() {
	*x = MultipleArticleReply_Article_Author{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleArticleReply_Article_Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleArticleReply_Article_Author) ProtoMessage() {}

func (x *MultipleArticleReply_Article_Author) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleArticleReply_Article_Author.ProtoReflect.Descriptor instead.
func (*MultipleArticleReply_Article_Author) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{18, 0, 0}
}

func (x *MultipleArticleReply_Article_Author) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MultipleArticleReply_Article_Author) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *MultipleArticleReply_Article_Author) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MultipleArticleReply_Article_Author) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type SingleCommentReply_Comment struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Id            int32                              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                             `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                             `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Body          string                             `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Author        *SingleCommentReply_Comment_Author `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleCommentReply_Comment) Reset() {
	*x = SingleCommentReply_Comment{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleCommentReply_Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleCommentReply_Comment) ProtoMessage() {}

func (x *SingleCommentReply_Comment) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleCommentReply_Comment.ProtoReflect.Descriptor instead.
func (*SingleCommentReply_Comment) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{19, 0}
}

func (x *SingleCommentReply_Comment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SingleCommentReply_Comment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SingleCommentReply_Comment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SingleCommentReply_Comment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SingleCommentReply_Comment) GetAuthor() *SingleCommentReply_Comment_Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type SingleCommentReply_Comment_Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following     bool                   `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleCommentReply_Comment_Author) Reset() {
	*x = SingleCommentReply_Comment_Author{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleCommentReply_Comment_Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleCommentReply_Comment_Author) ProtoMessage() {}

func (x *SingleCommentReply_Comment_Author) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleCommentReply_Comment_Author.ProtoReflect.Descriptor instead.
func (*SingleCommentReply_Comment_Author) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{19, 0, 0}
}

func (x *SingleCommentReply_Comment_Author) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SingleCommentReply_Comment_Author) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *SingleCommentReply_Comment_Author) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SingleCommentReply_Comment_Author) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type MultipleCommentReply_Comment struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Id            int32                                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                               `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                               `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Body          string                               `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Author        *MultipleCommentReply_Comment_Author `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleCommentReply_Comment) Reset() {
	*x = MultipleCommentReply_Comment{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleCommentReply_Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleCommentReply_Comment) ProtoMessage() {}

func (x *MultipleCommentReply_Comment) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleCommentReply_Comment.ProtoReflect.Descriptor instead.
func (*MultipleCommentReply_Comment) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{20, 0}
}

func (x *MultipleCommentReply_Comment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MultipleCommentReply_Comment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MultipleCommentReply_Comment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *MultipleCommentReply_Comment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MultipleCommentReply_Comment) GetAuthor() *MultipleCommentReply_Comment_Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type MultipleCommentReply_Comment_Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following     bool                   `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleCommentReply_Comment_Author) Reset() {
	*x = MultipleCommentReply_Comment_Author{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleCommentReply_Comment_Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleCommentReply_Comment_Author) ProtoMessage() {}

func (x *MultipleCommentReply_Comment_Author) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleCommentReply_Comment_Author.ProtoReflect.Descriptor instead.
func (*MultipleCommentReply_Comment_Author) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{20, 0, 0}
}

func (x *MultipleCommentReply_Comment_Author) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MultipleCommentReply_Comment_Author) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *MultipleCommentReply_Comment_Author) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MultipleCommentReply_Comment_Author) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

var File_realworld_v1_realworld_proto protoreflect.FileDescriptor

const file_realworld_v1_realworld_proto_rawDesc = "" +
	"\n" +
	"\x1crealworld/v1/realworld.proto\x12\frealworld.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"{\n" +
	"\vAuthRequest\x122\n" +
	"\x04user\x18\x01 \x01(\v2\x1e.realworld.v1.AuthRequest.UserR\x04user\x1a8\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x9f\x01\n" +
	"\x0fRegisterRequest\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".realworld.v1.RegisterRequest.UserR\x04user\x1aT\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\xcb\x01\n" +
	"\x11UpdateUserRequest\x128\n" +
	"\x04user\x18\x01 \x01(\v2$.realworld.v1.UpdateUserRequest.UserR\x04user\x1a|\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\"/\n" +
	"\x11GetProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"/\n" +
	"\x11FollowUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x8b\x01\n" +
	"\x13ListArticlesRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x1c\n" +
	"\tfavorited\x18\x03 \x01(\tR\tfavorited\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"C\n" +
	"\x13FeedArticlesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"'\n" +
	"\x11GetArticleRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"*\n" +
	"\x14DeleteArticleRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\xcd\x01\n" +
	"\x14CreateArticleRequest\x12D\n" +
	"\aarticle\x18\x01 \x01(\v2*.realworld.v1.CreateArticleRequest.ArticleR\aarticle\x1ao\n" +
	"\aArticle\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x18\n" +
	"\atagList\x18\x04 \x03(\tR\atagList\"\xc7\x01\n" +
	"\x14UpdateArticleRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12D\n" +
	"\aarticle\x18\x02 \x01(\v2*.realworld.v1.UpdateArticleRequest.ArticleR\aarticle\x1aU\n" +
	"\aArticle\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"\x8b\x01\n" +
	"\x12AddCommentsRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12B\n" +
	"\acomment\x18\x02 \x01(\v2(.realworld.v1.AddCommentsRequest.CommentR\acomment\x1a\x1d\n" +
	"\aComment\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"(\n" +
	"\x12GetCommentsRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\":\n" +
	"\x14DeleteCommentRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\",\n" +
	"\x16FavoriteArticleRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\xb5\x01\n" +
	"\tUserReply\x120\n" +
	"\x04user\x18\x01 \x01(\v2\x1c.realworld.v1.UserReply.UserR\x04user\x1av\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\"\xb9\x01\n" +
	"\fProfileReply\x12<\n" +
	"\aprofile\x18\x01 \x01(\v2\".realworld.v1.ProfileReply.ProfileR\aprofile\x1ak\n" +
	"\aProfile\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1c\n" +
	"\tfollowing\x18\x04 \x01(\bR\tfollowing\"\x95\x04\n" +
	"\x12SingleArticleReply\x12B\n" +
	"\aarticle\x18\x01 \x01(\v2(.realworld.v1.SingleArticleReply.ArticleR\aarticle\x1a\xba\x03\n" +
	"\aArticle\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x18\n" +
	"\atagList\x18\x05 \x03(\tR\atagList\x12\x1c\n" +
	"\tcreatedAt\x18\x06 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\a \x01(\tR\tupdatedAt\x12\x1c\n" +
	"\tfavorited\x18\b \x01(\bR\tfavorited\x12&\n" +
	"\x0efavoritesCount\x18\t \x01(\x05R\x0efavoritesCount\x12G\n" +
	"\x06author\x18\n" +
	" \x01(\v2/.realworld.v1.SingleArticleReply.Article.AuthorR\x06author\x1aj\n" +
	"\x06Author\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1c\n" +
	"\tfollowing\x18\x04 \x01(\bR\tfollowing\"\xaf\x04\n" +
	"\x14MultipleArticleReply\x12F\n" +
	"\barticles\x18\x01 \x03(\v2*.realworld.v1.MultipleArticleReply.ArticleR\barticles\x12$\n" +
	"\rarticlesCount\x18\x02 \x01(\x05R\rarticlesCount\x1a\xa8\x03\n" +
	"\aArticle\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\atagList\x18\x04 \x03(\tR\atagList\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\tR\tupdatedAt\x12\x1c\n" +
	"\tfavorited\x18\a \x01(\bR\tfavorited\x12&\n" +
	"\x0efavoritesCount\x18\b \x01(\x05R\x0efavoritesCount\x12I\n" +
	"\x06author\x18\t \x01(\v21.realworld.v1.MultipleArticleReply.Article.AuthorR\x06author\x1aj\n" +
	"\x06Author\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1c\n" +
	"\tfollowing\x18\x04 \x01(\bR\tfollowing\"\xf9\x02\n" +
	"\x12SingleCommentReply\x12B\n" +
	"\acomment\x18\x01 \x01(\v2(.realworld.v1.SingleCommentReply.CommentR\acomment\x1a\x9e\x02\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x03 \x01(\tR\tupdatedAt\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12G\n" +
	"\x06author\x18\x05 \x01(\v2/.realworld.v1.SingleCommentReply.Comment.AuthorR\x06author\x1aj\n" +
	"\x06Author\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1c\n" +
	"\tfollowing\x18\x04 \x01(\bR\tfollowing\"\x81\x03\n" +
	"\x14MultipleCommentReply\x12F\n" +
	"\bcomments\x18\x01 \x03(\v2*.realworld.v1.MultipleCommentReply.CommentR\bcomments\x1a\xa0\x02\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x03 \x01(\tR\tupdatedAt\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12I\n" +
	"\x06author\x18\x05 \x01(\v21.realworld.v1.MultipleCommentReply.Comment.AuthorR\x06author\x1aj\n" +
	"\x06Author\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1c\n" +
	"\tfollowing\x18\x04 \x01(\bR\tfollowing\"#\n" +
	"\rListTagsReply\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags2\xbc\x10\n" +
	"\tRealWorld\x12X\n" +
	"\x05Login\x12\x19.realworld.v1.AuthRequest\x1a\x17.realworld.v1.UserReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/users/login\x12Y\n" +
	"\bRegister\x12\x1d.realworld.v1.RegisterRequest\x1a\x17.realworld.v1.UserReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/users\x12T\n" +
	"\x0eGetCurrentUser\x12\x16.google.protobuf.Empty\x1a\x17.realworld.v1.UserReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/api/user\x12\\\n" +
	"\n" +
	"UpdateUser\x12\x1f.realworld.v1.UpdateUserRequest\x1a\x17.realworld.v1.UserReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\x1a\t/api/user\x12k\n" +
	"\n" +
	"GetProfile\x12\x1f.realworld.v1.GetProfileRequest\x1a\x1a.realworld.v1.ProfileReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/profiles/{username}\x12r\n" +
	"\n" +
	"FollowUser\x12\x1f.realworld.v1.FollowUserRequest\x1a\x1a.realworld.v1.ProfileReply\"'\x82\xd3\xe4\x93\x02!\"\x1f/api/profiles/{username}/follow\x12t\n" +
	"\fUnFollowUser\x12\x1f.realworld.v1.FollowUserRequest\x1a\x1a.realworld.v1.ProfileReply\"'\x82\xd3\xe4\x93\x02!*\x1f/api/profiles/{username}/follow\x12l\n" +
	"\fListArticles\x12!.realworld.v1.ListArticlesRequest\x1a\".realworld.v1.MultipleArticleReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/articles\x12q\n" +
	"\fFeedArticles\x12!.realworld.v1.FeedArticlesRequest\x1a\".realworld.v1.MultipleArticleReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/articles/feed\x12m\n" +
	"\n" +
	"GetArticle\x12\x1f.realworld.v1.GetArticleRequest\x1a .realworld.v1.SingleArticleReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/articles/{slug}\x12o\n" +
	"\rCreateArticle\x12\".realworld.v1.CreateArticleRequest\x1a .realworld.v1.SingleArticleReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/articles\x12v\n" +
	"\rUpdateArticle\x12\".realworld.v1.UpdateArticleRequest\x1a .realworld.v1.SingleArticleReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/api/articles/{slug}\x12i\n" +
	"\rDeleteArticle\x12\".realworld.v1.DeleteArticleRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/api/articles/{slug}\x12{\n" +
	"\vAddComments\x12 .realworld.v1.AddCommentsRequest\x1a .realworld.v1.SingleCommentReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/articles/{slug}/comments\x12z\n" +
	"\vGetComments\x12 .realworld.v1.GetCommentsRequest\x1a\".realworld.v1.MultipleCommentReply\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/articles/{slug}/comments\x12w\n" +
	"\rDeleteComment\x12\".realworld.v1.DeleteCommentRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$*\"/api/articles/{slug}/comments/{id}\x12\x80\x01\n" +
	"\x0fFavoriteArticle\x12$.realworld.v1.FavoriteArticleRequest\x1a .realworld.v1.SingleArticleReply\"%\x82\xd3\xe4\x93\x02\x1f\"\x1d/api/articles/{slug}/favorite\x12\x82\x01\n" +
	"\x11UnFavoriteArticle\x12$.realworld.v1.FavoriteArticleRequest\x1a .realworld.v1.SingleArticleReply\"%\x82\xd3\xe4\x93\x02\x1f*\x1d/api/articles/{slug}/favorite\x12Q\n" +
	"\aGetTags\x12\x16.google.protobuf.Empty\x1a\x1b.realworld.v1.ListTagsReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/api/tagsBY\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z$kratos-realworld/api/realworld/v1;v1b\x06proto3"

var (
	file_realworld_v1_realworld_proto_rawDescOnce sync.Once
	file_realworld_v1_realworld_proto_rawDescData []byte
)

func file_realworld_v1_realworld_proto_rawDescGZIP() []byte {
	file_realworld_v1_realworld_proto_rawDescOnce.Do(func() {
		file_realworld_v1_realworld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realworld_v1_realworld_proto_rawDesc), len(file_realworld_v1_realworld_proto_rawDesc)))
	})
	return file_realworld_v1_realworld_proto_rawDescData
}

var file_realworld_v1_realworld_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_realworld_v1_realworld_proto_goTypes = []any{
	(*AuthRequest)(nil),                         // 0: realworld.v1.AuthRequest
	(*RegisterRequest)(nil),                     // 1: realworld.v1.RegisterRequest
	(*UpdateUserRequest)(nil),                   // 2: realworld.v1.UpdateUserRequest
	(*GetProfileRequest)(nil),                   // 3: realworld.v1.GetProfileRequest
	(*FollowUserRequest)(nil),                   // 4: realworld.v1.FollowUserRequest
	(*ListArticlesRequest)(nil),                 // 5: realworld.v1.ListArticlesRequest
	(*FeedArticlesRequest)(nil),                 // 6: realworld.v1.FeedArticlesRequest
	(*GetArticleRequest)(nil),                   // 7: realworld.v1.GetArticleRequest
	(*DeleteArticleRequest)(nil),                // 8: realworld.v1.DeleteArticleRequest
	(*CreateArticleRequest)(nil),                // 9: realworld.v1.CreateArticleRequest
	(*UpdateArticleRequest)(nil),                // 10: realworld.v1.UpdateArticleRequest
	(*AddCommentsRequest)(nil),                  // 11: realworld.v1.AddCommentsRequest
	(*GetCommentsRequest)(nil),                  // 12: realworld.v1.GetCommentsRequest
	(*DeleteCommentRequest)(nil),                // 13: realworld.v1.DeleteCommentRequest
	(*FavoriteArticleRequest)(nil),              // 14: realworld.v1.FavoriteArticleRequest
	(*UserReply)(nil),                           // 15: realworld.v1.UserReply
	(*ProfileReply)(nil),                        // 16: realworld.v1.ProfileReply
	(*SingleArticleReply)(nil),                  // 17: realworld.v1.SingleArticleReply
	(*MultipleArticleReply)(nil),                // 18: realworld.v1.MultipleArticleReply
	(*SingleCommentReply)(nil),                  // 19: realworld.v1.SingleCommentReply
	(*MultipleCommentReply)(nil),                // 20: realworld.v1.MultipleCommentReply
	(*ListTagsReply)(nil),                       // 21: realworld.v1.ListTagsReply
	(*AuthRequest_User)(nil),                    // 22: realworld.v1.AuthRequest.User
	(*RegisterRequest_User)(nil),                // 23: realworld.v1.RegisterRequest.User
	(*UpdateUserRequest_User)(nil),              // 24: realworld.v1.UpdateUserRequest.User
	(*CreateArticleRequest_Article)(nil),        // 25: realworld.v1.CreateArticleRequest.Article
	(*UpdateArticleRequest_Article)(nil),        // 26: realworld.v1.UpdateArticleRequest.Article
	(*AddCommentsRequest_Comment)(nil),          // 27: realworld.v1.AddCommentsRequest.Comment
	(*UserReply_User)(nil),                      // 28: realworld.v1.UserReply.User
	(*ProfileReply_Profile)(nil),                // 29: realworld.v1.ProfileReply.Profile
	(*SingleArticleReply_Article)(nil),          // 30: realworld.v1.SingleArticleReply.Article
	(*SingleArticleReply_Article_Author)(nil),   // 31: realworld.v1.SingleArticleReply.Article.Author
	(*MultipleArticleReply_Article)(nil),        // 32: realworld.v1.MultipleArticleReply.Article
	(*MultipleArticleReply_Article_Author)(nil), // 33: realworld.v1.MultipleArticleReply.Article.Author
	(*SingleCommentReply_Comment)(nil),          // 34: realworld.v1.SingleCommentReply.Comment
	(*SingleCommentReply_Comment_Author)(nil),   // 35: realworld.v1.SingleCommentReply.Comment.Author
	(*MultipleCommentReply_Comment)(nil),        // 36: realworld.v1.MultipleCommentReply.Comment
	(*MultipleCommentReply_Comment_Author)(nil), // 37: realworld.v1.MultipleCommentReply.Comment.Author
	(*emptypb.Empty)(nil),                       // 38: google.protobuf.Empty
}
var file_realworld_v1_realworld_proto_depIdxs = []int32{
	22, // 0: realworld.v1.AuthRequest.user:type_name -> realworld.v1.AuthRequest.User
	23, // 1: realworld.v1.RegisterRequest.user:type_name -> realworld.v1.RegisterRequest.User
	24, // 2: realworld.v1.UpdateUserRequest.user:type_name -> realworld.v1.UpdateUserRequest.User
	25, // 3: realworld.v1.CreateArticleRequest.article:type_name -> realworld.v1.CreateArticleRequest.Article
	26, // 4: realworld.v1.UpdateArticleRequest.article:type_name -> realworld.v1.UpdateArticleRequest.Article
	27, // 5: realworld.v1.AddCommentsRequest.comment:type_name -> realworld.v1.AddCommentsRequest.Comment
	28, // 6: realworld.v1.UserReply.user:type_name -> realworld.v1.UserReply.User
	29, // 7: realworld.v1.ProfileReply.profile:type_name -> realworld.v1.ProfileReply.Profile
	30, // 8: realworld.v1.SingleArticleReply.article:type_name -> realworld.v1.SingleArticleReply.Article
	32, // 9: realworld.v1.MultipleArticleReply.articles:type_name -> realworld.v1.MultipleArticleReply.Article
	34, // 10: realworld.v1.SingleCommentReply.comment:type_name -> realworld.v1.SingleCommentReply.Comment
	36, // 11: realworld.v1.MultipleCommentReply.comments:type_name -> realworld.v1.MultipleCommentReply.Comment
	31, // 12: realworld.v1.SingleArticleReply.Article.author:type_name -> realworld.v1.SingleArticleReply.Article.Author
	33, // 13: realworld.v1.MultipleArticleReply.Article.author:type_name -> realworld.v1.MultipleArticleReply.Article.Author
	35, // 14: realworld.v1.SingleCommentReply.Comment.author:type_name -> realworld.v1.SingleCommentReply.Comment.Author
	37, // 15: realworld.v1.MultipleCommentReply.Comment.author:type_name -> realworld.v1.MultipleCommentReply.Comment.Author
	0,  // 16: realworld.v1.RealWorld.Login:input_type -> realworld.v1.AuthRequest
	1,  // 17: realworld.v1.RealWorld.Register:input_type -> realworld.v1.RegisterRequest
	38, // 18: realworld.v1.RealWorld.GetCurrentUser:input_type -> google.protobuf.Empty
	2,  // 19: realworld.v1.RealWorld.UpdateUser:input_type -> realworld.v1.UpdateUserRequest
	3,  // 20: realworld.v1.RealWorld.GetProfile:input_type -> realworld.v1.GetProfileRequest
	4,  // 21: realworld.v1.RealWorld.FollowUser:input_type -> realworld.v1.FollowUserRequest
	4,  // 22: realworld.v1.RealWorld.UnFollowUser:input_type -> realworld.v1.FollowUserRequest
	5,  // 23: realworld.v1.RealWorld.ListArticles:input_type -> realworld.v1.ListArticlesRequest
	6,  // 24: realworld.v1.RealWorld.FeedArticles:input_type -> realworld.v1.FeedArticlesRequest
	7,  // 25: realworld.v1.RealWorld.GetArticle:input_type -> realworld.v1.GetArticleRequest
	9,  // 26: realworld.v1.RealWorld.CreateArticle:input_type -> realworld.v1.CreateArticleRequest
	10, // 27: realworld.v1.RealWorld.UpdateArticle:input_type -> realworld.v1.UpdateArticleRequest
	8,  // 28: realworld.v1.RealWorld.DeleteArticle:input_type -> realworld.v1.DeleteArticleRequest
	11, // 29: realworld.v1.RealWorld.AddComments:input_type -> realworld.v1.AddCommentsRequest
	12, // 30: realworld.v1.RealWorld.GetComments:input_type -> realworld.v1.GetCommentsRequest
	13, // 31: realworld.v1.RealWorld.DeleteComment:input_type -> realworld.v1.DeleteCommentRequest
	14, // 32: realworld.v1.RealWorld.FavoriteArticle:input_type -> realworld.v1.FavoriteArticleRequest
	14, // 33: realworld.v1.RealWorld.UnFavoriteArticle:input_type -> realworld.v1.FavoriteArticleRequest
	38, // 34: realworld.v1.RealWorld.GetTags:input_type -> google.protobuf.Empty
	15, // 35: realworld.v1.RealWorld.Login:output_type -> realworld.v1.UserReply
	15, // 36: realworld.v1.RealWorld.Register:output_type -> realworld.v1.UserReply
	15, // 37: realworld.v1.RealWorld.GetCurrentUser:output_type -> realworld.v1.UserReply
	15, // 38: realworld.v1.RealWorld.UpdateUser:output_type -> realworld.v1.UserReply
	16, // 39: realworld.v1.RealWorld.GetProfile:output_type -> realworld.v1.ProfileReply
	16, // 40: realworld.v1.RealWorld.FollowUser:output_type -> realworld.v1.ProfileReply
	16, // 41: realworld.v1.RealWorld.UnFollowUser:output_type -> realworld.v1.ProfileReply
	18, // 42: realworld.v1.RealWorld.ListArticles:output_type -> realworld.v1.MultipleArticleReply
	18, // 43: realworld.v1.RealWorld.FeedArticles:output_type -> realworld.v1.MultipleArticleReply
	17, // 44: realworld.v1.RealWorld.GetArticle:output_type -> realworld.v1.SingleArticleReply
	17, // 45: realworld.v1.RealWorld.CreateArticle:output_type -> realworld.v1.SingleArticleReply
	17, // 46: realworld.v1.RealWorld.UpdateArticle:output_type -> realworld.v1.SingleArticleReply
	38, // 47: realworld.v1.RealWorld.DeleteArticle:output_type -> google.protobuf.Empty
	19, // 48: realworld.v1.RealWorld.AddComments:output_type -> realworld.v1.SingleCommentReply
	20, // 49: realworld.v1.RealWorld.GetComments:output_type -> realworld.v1.MultipleCommentReply
	38, // 50: realworld.v1.RealWorld.DeleteComment:output_type -> google.protobuf.Empty
	17, // 51: realworld.v1.RealWorld.FavoriteArticle:output_type -> realworld.v1.SingleArticleReply
	17, // 52: realworld.v1.RealWorld.UnFavoriteArticle:output_type -> realworld.v1.SingleArticleReply
	21, // 53: realworld.v1.RealWorld.GetTags:output_type -> realworld.v1.ListTagsReply
	35, // [35:54] is the sub-list for method output_type
	16, // [16:35] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_realworld_v1_realworld_proto_init() }
func file_realworld_v1_realworld_proto_init() {
	if File_realworld_v1_realworld_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realworld_v1_realworld_proto_rawDesc), len(file_realworld_v1_realworld_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realworld_v1_realworld_proto_goTypes,
		DependencyIndexes: file_realworld_v1_realworld_proto_depIdxs,
		MessageInfos:      file_realworld_v1_realworld_proto_msgTypes,
	}.Build()
	File_realworld_v1_realworld_proto = out.File
	file_realworld_v1_realworld_proto_goTypes = nil
	file_realworld_v1_realworld_proto_depIdxs = nil
}
